spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
#          show-sql: true
        show_sql: true

#          region.factory_class: jcache
#  cache:
#    jcache:
#      config: classpath:ehcache.xml
#    type: jcache








#  data:
#    redis:
#      host: localhost
#      port: 6379
